#!/bin/bash

[ $# -lt 1 ] && {
	echo "USAGE $0 <username>"
	exit 127
}

USER_CN=$1
ALG=ecdsa
COMMENT="Auto-generated by CA"
KEY_FILE="user_key"

ssh-keygen -t ${ALG} -C "${COMMENT}" -f ${KEY_FILE} -N ''

./sign_ssh_clientkeys.sh "${USER_CN}" "${KEY_FILE}"
